name: sems-exporter
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10,<3.13
  - requests>=2.31
  - python-dotenv>=1.0
  - pandas>=2.0
  - pyarrow>=15.0
  - fastparquet>=2024.2.0
  - matplotlib>=3.8
  - jupyter>=1.0
  - nbformat>=5.10
